### ISSUE TITLE
Prod appears to be down

### ISSUE THREAD

**Issue by milogert** [helldivers-companion/api#28]
## Describe the bug

Navigate to https://api-hellhub-collective.koyeb.app/api/war, see that you get a 404.

### Environment information

N/A

### Expected behavior

No 404 is produced.

### Which version of the browser are you using?

Safari 17.3.1 (19617.2.4.11.12)

### What areas are affected by the issue

- [ ] All areas
- [x] Production
- [ ] Staging
- [ ] Development

**Comment by fabio-nettis** [comment]
Closing as duplicate of #27.

**Comment by fabio-nettis** [comment]
Closing as duplicate of #27.
