### ISSUE TITLE
Docs: Outline key differences to other projects

### ISSUE THREAD

**Issue by stevenaldinger** [helldivers-companion/api#60]
## Describe the bug

No acknowledgment of similar projects in the README.

### Expected behavior

A list of other projects like https://github.com/helldivers-2/api with a description of what this project is solving that the others are not or when it'd be appropriate to use this over more established projects.

**Comment by fabio-nettis** [comment]
@stevenaldinger - Other projects are merely a wrapper around the official Arrowhead Game API. We provide better data structure, a sophisticated query system as well as a battalion of extra endpoints. You are more than welcome to open a PR outlining the key differences.

It is important the community can freely decide what API they would like to use and not to "steal" traffic from other projects as they are as valid and cool as ours. 🤘🏻
